sudo: required

language: python
python:
  - "3.6" 

services:
  - docker

before_install:
 # - docker build -t samneirinck/yons-musicservice musicservice

install: 
  - pip install pylint
  - pip install -r register/requirements.txt
  - pip install -r musicservice/requirements.txt

script:
  - docker build -t samneirinck/yons-musicservice musicservice
  # - pylint register/register.py
  # - pylint musicservice/musicservice.py

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push samneirinck/yons-musicservice;
    fi
