version: "2"
services: 
  # register:
  #   build: register
  #   volumes:
  #     - ./register:/code
  #   network_mode: "host"
  music-service:
    build: musicservice
    volumes:
      - ./musicservice:/code
    ports:
      - "8085:8085"
  